language: node_js

python:
  - 3.7

services:
  - docker

install:
  - pip install -r requirements.txt

jobs:
  include:
    - stage: deploy
      name: Docker image build
      script: skip
      deploy:
      - provider: script
        skip_cleanup: true
        script: .travis/build-and-push.sh
        on:
          branch: master
