CREATE TABLE hotels (
	City VARCHAR(255) NOT NULL,
	Name VARCHAR(255) NOT NULL,
	Country VARCHAR(255) NOT NULL,
	Superchain VARCHAR(255) NOT NULL,
	Cost decimal NOT NULL,
	Images TEXT [] NOT NULL,
	Type VARCHAR(255) NOT NULL
);